# Generated by Django 5.2.15 on 2026-07-23 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_alter_category_options_course_is_free_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quiz_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assignment_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.course')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_student_progress',
                'ordering': ['-last_accessed_at'],
            },
        ),
    ]
