# Generated by Django 5.2.15 on 2026-07-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enrollment',
            table='courses_enrollment',
        ),
    ]
