# Generated by Django 5.2.15 on 2026-07-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_auto_20260716_2124'),
    ]

    operations = [
    ]
