# Generated by Django 5.2.15 on 2026-07-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_enrollment_is_active_enrollment_progress_percentage_and_more'),
    ]

    operations = [
    ]
