# Generated by Django 5.2.15 on 2026-07-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='courses_category',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses_course',
        ),
        migrations.AlterModelTable(
            name='learningmaterial',
            table='courses_learning_materials',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='courses_lessons',
        ),
        migrations.AlterModelTable(
            name='module',
            table='courses_modules',
        ),
        migrations.AlterModelTable(
            name='videolink',
            table='courses_video_links',
        ),
    ]
