# Generated by Django 5.2.15 on 2026-07-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_category_table_alter_course_table_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.RemoveField(
            model_name='videolink',
            name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'category'},
        ),
        migrations.DeleteModel(
            name='LearningMaterial',
        ),
    ]
