# Generated by Django 5.2.15 on 2026-07-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_unique_together_remove_lesson_module_and_more'),

    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='VideoLink',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
