# Generated by Django 5.2.15 on 2026-07-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
