# Generated by Django 5.2.15 on 2026-07-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module',
            table='lessons_modules',
        ),
    ]
