# Generated by Django 5.2.15 on 2026-07-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_module_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module',
            table='lessons_module',
        ),
    ]
